import Layout from "../components/Layout";
import Head from "next/head";

import Link from "next/link";
import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";

const Concept = () => {
  return (
    <Layout>
      <Head>
        <title>Concept - Residence Kimpinski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section
        id="concept"
        className="w-full h-screen relative flex justify-center items-center overflow-hidden bg-[url('/assets/concept/concept1.jpg')] bg-no-repeat bg-cover bg-top"
      >
        <div className="w-full h-full bg-gradient-to-b from-black absolute opacity-75 " />
        <div className="max-w-7xl h-full w-full relative mx-4 md:mx-10 flex justify-center  ">
          <div className="mt-20 flex w-full absolute top-0">
            <img
              src="/assets/logo.svg"
              alt="logo"
              className="object-contain w-28 h-28"
            />
          </div>
          <p className="text-[150px] font-Heleness  text-[#B6A694] drop-shadow pt-44">
            C<span className="text-[90px] align-text-top">O</span>
            NC
            <span className="text-[90px] align-text-top">E</span>PT
          </p>
          <div></div>
        </div>
      </section>
    </Layout>
  );
};

export default Concept;
