import Layout from "../components/Layout";
import Head from "next/head";
import React, { useState, useEffect } from "react";

import { Fancybox, Carousel, Panzoom } from "@fancyapps/ui";


const Gallery = () => {

    return (
        <Layout>
            <Head>
                <title>Gallery - Residences Sindhorn Kempinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section
                id="gallery"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden bg-[url('/assets/gallery/gallery.jpg')] bg-no-repeat bg-cover bg-center"
            >
                <div className="w-full h-full bg-gradient-to-b from-black absolute opacity-30 " />
                <div className="max-w-7xl h-full w-full relative mx-4 md:mx-10 flex justify-center  ">
                    <div className="mt-20 flex w-full absolute top-0">
                        <img
                            src="/assets/logo.svg"
                            alt="logo"
                            className="object-contain w-28 h-28"
                        />
                    </div>
                    <p className="text-[150px] font-Heleness  text-[#F5F1EA] drop-shadow pt-44">
                        G<span className="text-[90px] align-text-top">A</span>
                        LL
                        <span className="text-[90px] align-text-top">E</span>RY
                    </p>
                    <div></div>
                </div>
            </section>

        </Layout>
    );
}

export default Gallery;