import Layout from "../components/Layout";
import Head from "next/head";
import React, { useState, useEffect } from "react";

import { Fancybox, Carousel, Panzoom } from "@fancyapps/ui";


const Gallery = () => {
    useEffect(() => {
        const thumbCarousel = new Carousel(document.querySelector("#thumbCarousel"), {
            Sync: {
                target: mainCarousel,
            },

            Dots: false,
            Navigation: false,

            infinite: false,
            center: true,
            slidesPerPage: 1,
        });

    }, [])

    useEffect(() => {
        const mainCarousel = new Carousel(document.querySelector("#mainCarousel"), {
            Dots: false,
        })

    })

    useEffect(() => {
        Fancybox.bind('[data-fancybox="gallery"]', {
            Toolbar: {
                display: [
                    { id: "prev", position: "center" },
                    { id: "counter", position: "center" },
                    { id: "next", position: "center" },
                    "zoom",
                    "slideshow",
                    "fullscreen",
                    "download",
                    "thumbs",
                    "close",
                ],
            },
            Carousel: {
                on: {
                    change: (that) => {
                        mainCarousel.slideTo(mainCarousel.findPageForSlide(that.page), {
                            friction: 0,
                        });
                    },
                },
            },

        });
    })



    return (
        <Layout>
            <Head>
                <title>Gallery - Residences Sindhorn Kempinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full bg-white flex justify-center">
                <div className="min-h-screen w-full h-full   max-w-7xl  py-10 relative mt-14 ">

                    <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-center font-Libre text-3xl">Photo Gallery</p>
                        <fieldset className="md:w-[600px] border-t border-[#B5A191] text-center mb-5">
                            <legend className="px-4">Explore The Residence at Sindhorn Kempinski</legend>
                        </fieldset>

                        <div id="mainCarousel" className="w-[800px] carousel  max-w-5xl mx-auto">
                            <div
                                className="carousel__slide"
                                data-src="https://lipsum.app/id/1/900x600"
                                data-fancybox="gallery"
                                data-caption="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum lobortis ultricies ipsum, a maximus ligula dignissim in. Sed consectetur tellus egestas, consequat dolor at, tempus augue. Morbi quis ipsum quis velit."
                            >
                                <img src="https://lipsum.app/id/1/600x400" alt="slide" className="object-cover w-full h-full" />
                            </div>
                            <div
                                className="carousel__slide"
                                data-src="https://lipsum.app/id/2/900x600"
                                data-fancybox="gallery"
                                data-caption="Ut semper, justo eget vehicula vestibulum, enim enim suscipit lectus, et sagittis nibh risus vel metus. Quisque eu ornare ante, et gravida mauris"
                            >
                                <img src="https://lipsum.app/id/2/600x400" alt="slide" className="object-cover w-full h-full" />
                            </div>
                            <div
                                className="carousel__slide"
                                data-src="https://lipsum.app/id/3/900x600"
                                data-fancybox="gallery"
                                data-caption="Hello 🖐"
                            >
                                <img src="https://lipsum.app/id/3/600x400" alt="slide" className="object-cover w-full h-full" />
                            </div>
                            <div
                                className="carousel__slide"
                                data-src="https://lipsum.app/id/4/900x600"
                                data-fancybox="gallery"
                                data-caption="Another caption"
                            >
                                <img src="https://lipsum.app/id/4/600x400" alt="slide" className="object-cover w-full h-full" />
                            </div>
                            <div
                                className="carousel__slide"
                                data-src="https://lipsum.app/id/5/900x600"
                                data-fancybox="gallery"
                            >
                                <img data-lazy-src="https://lipsum.app/id/5/600x400" alt="slide" className="object-cover w-full h-full" />
                            </div>
                            <div
                                className="carousel__slide"
                                data-src="https://lipsum.app/id/6/900x600"
                                data-fancybox="gallery"
                            >
                                <img src="https://lipsum.app/id/6/600x400" alt="slide" className="object-cover w-full h-full" />
                            </div>
                            <div
                                className="carousel__slide"
                                data-src="https://lipsum.app/id/7/900x600"
                                data-fancybox="gallery"
                            >
                                <img src="https://lipsum.app/id/7/600x400" alt="slide" className="object-cover w-full h-full" />
                            </div>
                        </div>

                        <div id="thumbCarousel" className="mt-5 carousel  mx-auto">
                            <div className="carousel__slide">
                                <img className="panzoom__content" src="https://lipsum.app/id/1/100x100" alt="thumb" />
                            </div>
                            <div className="carousel__slide">
                                <img className="panzoom__content" src="https://lipsum.app/id/2/100x100" alt="thumb" />
                            </div>
                            <div className="carousel__slide">
                                <img className="panzoom__content" src="https://lipsum.app/id/3/100x100" alt="thumb" />
                            </div>
                            <div className="carousel__slide">
                                <img className="panzoom__content" src="https://lipsum.app/id/4/100x100" alt="thumb" />
                            </div>
                            <div className="carousel__slide">
                                <img className="panzoom__content" src="https://lipsum.app/id/5/100x100" alt="thumb" />
                            </div>
                            <div className="carousel__slide">
                                <img className="panzoom__content" src="https://lipsum.app/id/6/100x100" alt="thumb" />
                            </div>
                            <div className="carousel__slide">
                                <img className="panzoom__content" src="https://lipsum.app/id/7/100x100" alt="thumb" />
                            </div>
                        </div>
                    </section>

                </div>



            </div>
        </Layout>
    );
}

export default Gallery;