import Layout from "../components/Layout";
import Head from "next/head";
import React, { useState, useEffect } from "react";
import Image from 'next/image'
import { Autoplay } from "@fancyapps/ui/dist/carousel.autoplay.esm.js";
import { Fancybox, Carousel, Panzoom } from "@fancyapps/ui";

Carousel.Plugins.Autoplay = Autoplay;
Fancybox.defaults.ScrollLock = false;
const newsFB = [
    { id: 1, name: "", description: "", image: "" },
    { id: 2, name: "", description: "", image: "" },
    { id: 3, name: "", description: "", image: "" },
    { id: 4, name: "", description: "", image: "" },
    { id: 5, name: "", description: "", image: "" },
    { id: 6, name: "", description: "", image: "" },
    { id: 7, name: "", description: "", image: "" },

]

const News = () => {
    useEffect(() => {
        setTimeout(() => {
            const mainCarousel = new Carousel(document.querySelector("#mainCarousel"), {
                friction: 0.96,
                center: true,
                Autoplay: {
                    timeout: 1000,
                    hoverPause: true,
                },
            }, 2000);
        })
    });

    return (

        <Layout>
            <Head>
                <title>News - Residences Sindhorn Kempinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full bg-white flex justify-center">
                <div className="min-h-screen w-full h-full  max-w-7xl  py-10 relative mt-14 px-4 md:px-10">
                    <div className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-center font-Libre text-3xl">News update</p>
                        <fieldset className="md:w-[600px] border-t border-[#B5A191] text-center mb-5">
                            <legend className="px-4">Explore The Residence at Sindhorn Kempinski</legend>
                        </fieldset>
                    </div>
                    <div id="mainCarousel" className="carousel  mx-auto py-5 max-h-[300px] sm:max-h-[600px] overflow-hidden ">
                        <div className="carousel__viewport">
                            {newsFB.map((item, index) => (
                                <div key={index} className="carousel__slide md:!w-full min-h-[350px] sm:min-h-[600px] md:mx-auto rounded shadow bg-black">11</div>

                            ))}



                        </div>
                    </div>
                    <fieldset className="md:w-[300px] border-t border-[#B5A191]  my-5">
                        <legend className="px-4 font-Libre text-xl font-medium">News</legend>
                    </fieldset>
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                        {newsFB.map((item, index) => (
                            <div key={index} className="w-full min-h-[250px] bg-black">11</div>

                        ))}

                    </div>
                    <fieldset className="md:w-[300px] border-t border-[#B5A191]  my-5">
                        <legend className="px-4 font-Libre text-xl font-medium">Article</legend>
                    </fieldset>
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                        {newsFB.map((item, index) => (
                            <div key={index} className="w-full min-h-[250px] bg-black">11</div>

                        ))}

                    </div>
                </div>
            </div>
        </Layout>
    );
}

export default News;