import Layout from "../components/Layout";
<<<<<<< HEAD
import Head from "next/head";
import React, { useState, useEffect } from "react";
import Image from 'next/image'
import { Autoplay } from "@fancyapps/ui/dist/carousel.autoplay.esm.js";
import { Fancybox, Carousel, Panzoom } from "@fancyapps/ui";

Carousel.Plugins.Autoplay = Autoplay;
Fancybox.defaults.ScrollLock = false;
const newsFB = [
    { id: 1, name: "", description: "", image: "" },
    { id: 2, name: "", description: "", image: "" },
    { id: 3, name: "", description: "", image: "" },
    { id: 4, name: "", description: "", image: "" },
    { id: 5, name: "", description: "", image: "" },
    { id: 6, name: "", description: "", image: "" },
    { id: 7, name: "", description: "", image: "" },

]

=======
import Footer from "../components/Footer";
>>>>>>> dev
const News = () => {
    useEffect(() => {
        setTimeout(() => {
            const mainCarousel = new Carousel(document.querySelector("#mainCarousel"), {
                friction: 0.96,
                center: true,
                Autoplay: {
                    timeout: 1000,
                    hoverPause: true,
                },
            }, 2000);
        })
    });

    return (

        <Layout>
<<<<<<< HEAD
            <Head>
                <title>News - Residences Sindhorn Kempinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-full bg-white flex justify-center">
                <div className="min-h-screen w-full h-full  max-w-7xl  py-10 relative mt-14 px-4 md:px-10">
                    <div className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
                        <p className="text-center font-Libre text-3xl">News update</p>
                        <fieldset className="md:w-[600px] border-t border-[#B5A191] text-center mb-5">
                            <legend className="px-4">Explore The Residence at Sindhorn Kempinski</legend>
                        </fieldset>
                    </div>
                    <div id="mainCarousel" className="carousel  mx-auto py-5 max-h-[300px] sm:max-h-[600px] overflow-hidden ">
                        <div className="carousel__viewport">
                            {newsFB.map((item, index) => (
                                <div key={index} className="carousel__slide md:!w-full min-h-[350px] sm:min-h-[600px] md:mx-auto rounded shadow bg-black">11</div>

                            ))}



                        </div>
                    </div>
                    <fieldset className="md:w-[300px] border-t border-[#B5A191]  my-5">
                        <legend className="px-4 font-Libre text-xl font-medium">News</legend>
                    </fieldset>
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                        {newsFB.map((item, index) => (
                            <div key={index} className="w-full min-h-[250px] bg-black">11</div>

                        ))}

                    </div>
                    <fieldset className="md:w-[300px] border-t border-[#B5A191]  my-5">
                        <legend className="px-4 font-Libre text-xl font-medium">Article</legend>
                    </fieldset>
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
                        {newsFB.map((item, index) => (
                            <div key={index} className="w-full min-h-[250px] bg-black">11</div>

                        ))}

                    </div>
                </div>
=======
            <section
                id="news"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden bg-[url('/assets/news/news.jpg')] bg-no-repeat bg-cover bg-center"
            >
                <div className="w-full h-full bg-gradient-to-b from-black absolute opacity-75" />
                <div className="max-w-7xl h-full w-full relative mx-4 md:mx-10 flex justify-center  ">
                    <div className="mt-20 flex w-full absolute top-0">
                        <img
                            src="/assets/logo.svg"
                            alt="logo"
                            className="object-contain w-28 h-28"
                        />
                    </div>
                    <p className="text-[150px] font-Heleness  text-[#F5F1EA] drop-shadow pt-44">
                        N<span className="text-[90px] align-text-top">E</span>
                        WS

                    </p>
                    <div></div>
                </div>
            </section>

            <div className="bg-[#F5F1EA] w-full h-full pt-52">
                <Footer />
>>>>>>> dev
            </div>
        </Layout>
    );
}

export default News;