import Head from 'next/head'
import Layout from "../components/Layout";
import Footer from "../components/Footer";

const Register = () => {
    return (
        <Layout>
            <Head>
                <title>Register - Residences Sindhorn Kempinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section
                id="enquiry"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden bg-[url('/assets/register.jpg')] bg-no-repeat bg-cover bg-center"
            >
                <div className="w-full h-full bg-gradient-to-b from-black absolute opacity-30 " />
                <div className="max-w-7xl h-full w-full relative mx-4 md:mx-10 flex justify-center  ">
                    <div className="mt-20 flex w-full absolute top-0">
                        <img
                            src="/assets/logo.svg"
                            alt="logo"
                            className="object-contain w-28 h-28"
                        />
                    </div>
                    <p className="text-[150px] font-Heleness  text-[#F5F1EA] drop-shadow pt-44">
                        <span className="text-[90px] align-text-top">E</span>
                        NQ
                        <span className="text-[90px] align-text-top">U</span>IRY
                    </p>
                    <div></div>
                </div>
            </section>

            <section id="register" className="snap-start h-screen w-full  bg-[url('/assets/background.jpg')] bg-cover bg-no-repeat bg-fixed relative">
                <div className="w-full h-full  absolute bg-[url('/assets/background.jpg')] bg-cover bg-no-repeat" />
                <div className="w-full h-full  absolute bg-[url('/assets/manifestobg.png')] bg-contain  bg-no-repeat opacity-20 " />

                <div className="w-full h-full  absolute  flex flex-col justify-between items-center ">
                    <div className="max-w-7xl w-full h-full flex flex-col items-center pt-16 text-[#B5A191] gap-3">
                        <img
                            src="/assets/logo.svg"
                            alt="logo"
                            className="object-contain w-28 h-28"
                        />

                        <p className="text-3xl text-center">
                            ENQUIRY / FOR BROCHURE
                        </p>
                        <p className="text-center">
                            Please enter your registration details in the corresponding fields.<br></br>
                            Click submit button to download the brochure.
                        </p>
                        <p className="text-center">
                            I dont have a permanent address in Thailand.
                        </p>

                        <form action="">
                            <div className='px-8 pt-6 grid grid-cols-1 md:grid-cols-2 gap-2'>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="name">
                                        First Name
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="name" type="text" placeholder="Name" required />
                                </div>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="Lname">
                                        Last Name
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="Lname" type="text" placeholder="Lastname" required />
                                </div>

                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="email">
                                        Email
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" placeholder="Email" required />
                                </div>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="phone">
                                        Phone Number
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="phone" type="tel" placeholder="Phone number" />
                                </div>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="typeUnit">
                                        Unit Type
                                    </label>
                                    <div className="relative">
                                        <select className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-3 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="typeUnit"
                                            defaultValue="">
                                            <option value="" disabled > Unit Type </option>
                                            <option value="1 Bedroom" >1 Bedroom</option>
                                            <option value="2 Bedroom">2 Bedroom</option>
                                            <option value="3 Bedroom">3 Bedroom</option>
                                            <option value="Penthouse">Penthouse</option>
                                        </select>
                                        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                            <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /></svg>
                                        </div>
                                    </div>
                                </div>

                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="price">
                                        Price
                                    </label>
                                    <div className="relative">
                                        <select className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-3 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="price"
                                            defaultValue="">
                                            <option value="" disabled > Price </option>
                                            <option value="less than 20 Million Baht" >Less than 20 Million Baht</option>
                                            <option value="21-30 Million Baht">21-30 Million Baht</option>
                                            <option value="31-40 Million Baht">31-40 Million Baht</option>
                                            <option value="41-50 Million Baht">41-50 Million Baht</option>
                                            <option value="more than 50 Million Baht">More than 50 Million Baht</option>
                                        </select>
                                        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                            <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /></svg>
                                        </div>
                                    </div>
                                </div>

                                <div className="mb-2 md:col-span-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="message">
                                        Message
                                    </label>
                                    <textarea className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="message" type="text" placeholder="Tell us what you're thinking about..." />
                                </div>

                            </div>

                        </form>

                        <p className="text-center">
                            Sindhorn Village Members Card click here for special privilege
                        </p>

                        <div>
                            <button className="text-white w-fit px-4 py-2 bg-[#97233F]">SUBMIT</button>
                        </div>
                    </div>
                    <div className=" w-full  flex justify-end items-end">
                        <Footer />
                    </div>
                </div>
            </section>





            {/* <div className=' min-h-screen h-full w-full flex justify-center'>


                <div className="max-w-7xl w-full h-full flex justify-center p-4 mt-10">
                    <div className="w-full relative  mx-1 md:mx-8 h-full">

                        <div className="py-12 w-full flex justify-center items-center flex-col px-8">
                            <img src="/assets/kempinski-way-of-living-banner.png" alt="banner" className="object-cover w-auto" />
                            <p className="font-Libre  text-xl md:text-3xl text-white text-center mt-5">Super Luxury Condominium <br></br>Serviced by Kempinski</p>
                        </div>

                        <p className="text-white px-8">Register to receive special privileges</p>
                        <form action="">
                            <div className='px-8 pt-6 grid grid-cols-1 md:grid-cols-2 gap-2'>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="name">
                                        First Name
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="name" type="text" placeholder="Name" required />
                                </div>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="Lname">
                                        Last Name
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="Lname" type="text" placeholder="Lastname" required />
                                </div>

                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="email">
                                        Email
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" placeholder="Email" required />
                                </div>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="phone">
                                        Phone Number
                                    </label>
                                    <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="phone" type="tel" placeholder="Phone number" />
                                </div>
                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="typeUnit">
                                        Unit Type
                                    </label>
                                    <div className="relative">
                                        <select className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-3 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="typeUnit"
                                            defaultValue="">
                                            <option value="" disabled > Unit Type </option>
                                            <option value="1 Bedroom" >1 Bedroom</option>
                                            <option value="2 Bedroom">2 Bedroom</option>
                                            <option value="3 Bedroom">3 Bedroom</option>
                                            <option value="Penthouse">Penthouse</option>
                                        </select>
                                        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                            <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /></svg>
                                        </div>
                                    </div>
                                </div>

                                <div className="mb-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="price">
                                        Price
                                    </label>
                                    <div className="relative">
                                        <select className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-2 px-3 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="price"
                                            defaultValue="">
                                            <option value="" disabled > Price </option>
                                            <option value="less than 20 Million Baht" >Less than 20 Million Baht</option>
                                            <option value="21-30 Million Baht">21-30 Million Baht</option>
                                            <option value="31-40 Million Baht">31-40 Million Baht</option>
                                            <option value="41-50 Million Baht">41-50 Million Baht</option>
                                            <option value="more than 50 Million Baht">More than 50 Million Baht</option>
                                        </select>
                                        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                            <svg className="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /></svg>
                                        </div>
                                    </div>
                                </div>

                                <div className="mb-2 md:col-span-2">
                                    <label className="block text-[#B6A694] text-sm font-bold mb-2" htmlFor="message">
                                        Message
                                    </label>
                                    <textarea className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="message" type="text" placeholder="Tell us what you're thinking about..." />
                                </div>

                                <div className="grid justify-items-center md:col-span-2 ">

                                    <div className="space-x-2">

                                        <button className='rounded-none bg-transparent border-2 border-[#B6A694] w-[120px] h-[30px] text-[#B6A694] inline-flex items-center justify-center hover:bg-[#B6A694] hover:text-white'> Submit

                                        </button>


                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>

                </div>

            </div> */}
        </Layout>
    );
}

export default Register;