import Layout from "../components/Layout";
import Head from "next/head";
import Slider from "react-slick";
import Footer from "../components/Footer";
import React, { useState, useEffect } from "react";
import { Link, animateScroll as scroll, scroller } from 'react-scroll'

const Service = () => {
    var settings = {
        speed: 1400,
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
        dots: true,
        infinite: true,
        fade: true,
    };

    var settings2 = {
        speed: 1400,
        centerMode: true,
        centerPadding: '250px',
        slidesToShow: 1,

        slidesToScroll: 1,
        arrows: true,
        dots: true,

    };

    const checkClick = () => {
        console.log("Clicked");
    }


    useEffect(() => {
        const btn = document.getElementById("button");
        setTimeout(() => {
            if (window.scrollY <= 500) {
                btn.click();
            }
        }, 5000)
    })

    return (
        <Layout>
            <Head>
                <title>Service - Residence Kimpinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section
                id="service"
                className="snap-start w-full h-[120vh] relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-full bg-gradient-to-b from-[#B5A191] absolute opacity-10 z-10" />
                <div className="max-w-7xl h-full w-full relative mx-4 md:mx-10 flex justify-center z-10">
                    <div className="mt-20 flex w-full absolute top-0 z-30">
                        <img
                            src="/assets/logo-w.svg"
                            alt="logo"
                            className="object-contain w-28 h-28"
                        />
                    </div>
                    <p className="text-[150px] font-Heleness  text-white pt-44">
                        S<span className="text-[90px] align-text-top">E</span>
                        RV
                        <span className="text-[90px] align-text-top">I</span>CE
                    </p>
                </div>
                <div id="content" className="snap-start w-full h-[120vh] bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-[120vh]  ">
                        <div className="w-full h-[120vh]  bg-[url('/assets/service/service1.jpg')] bg-cover bg-center bg-no-repeat" />
                    </Slider>
                </div>

                <Link
                    activeClass="active"
                    to="kempinService"
                    spy={true}
                    offset={-64}
                    smooth={true}
                    duration={1000}
                >

                    <button id="button" onClick={checkClick} className="arrow  cursor-pointer z-40 -translate-y-36">
                        <svg height="25" width="50" className="animate-bounce">

                            <polygon
                                points="0,0 25,10 50,0 25,25"
                                fill="#fff"
                                strokeWidth="0"
                                stroke="rgba(255,255,255,.3)"
                            />
                        </svg>

                        {/* <div className="progress-1 -translate-x-9 mt-5"></div> */}
                    </button>
                </Link>

            </section>



            <section id="kempinService" className="snap-start w-full h-screen relative flex justify-center items-center  bg-[#B6A694] bg-fixed mb-4 ">
                <div className="w-1/2 h-full absolute bg-[url('/assets/manifestobg-f.png')] bg-cover bg-no-repeat right-0 bg-left-top opacity-50">

                </div>
                <div className="max-w-7xl w-full h-full absolute ">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 w-full h-full">
                        <div className="grid grid-cols-2 content-center">
                            <div className="w-52 h-52 md:w-80 md:h-96  p-2 ">
                                <img src="assets/service/kempinski.jpg" alt="kempin" className="object-cover w-full h-full object-center" />
                            </div>
                            <div className="w-52 h-52 md:w-80 md:h-96 p-2 ">
                                <img src="assets/service/kempinski4.jpg" alt="kempin" className="object-cover w-full h-full object-center" />
                            </div>
                            <div className="w-52 h-52 md:w-80 md:h-96  p-2">
                                <img src="assets/service/kempinski3.jpg" alt="kempin" className="object-cover w-full h-full object-center" />
                            </div>
                            <div className="w-52 h-52 md:w-80 md:h-96  p-2">
                                <img src="assets/service/kempinski2.jpg" alt="kempin" className="object-cover w-full h-full object-center" />
                            </div>



                        </div>
                        <div className="w-full h-full flex flex-col justify-center items-center">
                            <div className="w-full pl-20">
                                <p className="pl-16 text-xs uppercase">serviced by</p>

                                <img src="/assets/corp_logo_websit.svg" alt="kempinski" className="object-contain h-28 -translate-y-8 " />
                            </div>
                            <ul className="list-disc font-kingsCaslon -translate-y-12">
                                <li>
                                    Property management provided by Kempinski
                                </li>
                                <li>
                                    24-hour Concierge/Reception
                                </li>
                                <li>
                                    Doormen
                                </li>
                                <li>
                                    Shuttle services
                                </li>
                                <li>
                                    Security guards / 24-hour centralized TV surveillance systems
                                </li>
                                <li>
                                    Fitness Trainer/ Masseuse
                                </li>
                                <li>
                                    Trolley cart services
                                </li>
                                <li>
                                    Local & International postage and shipping services
                                </li>
                                <li>
                                    Tenancy services
                                </li>
                                <li>
                                    Homecare program and maintenance services
                                </li>
                                <li>
                                    Resident assistance services
                                </li>
                                <li>
                                    Laundry (upon request with extra charge)
                                </li>
                                <li>
                                    Housekeeping (upon request with extra charge)
                                </li>
                                <li>
                                    Exclusive hotel services (upon request with extra charge)
                                </li>

                            </ul>
                        </div>

                    </div>

                </div>

            </section>

            <section
                id="service2"
                className="
                snap-start h-screen w-full bg-[url('/assets/paper.jpg')] bg-cover bg-no-repeat bg-fixed relative
                 flex justify-center items-center overflow-hidden mb-4"
            >

                <div id="content" className="mb-96 snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/service2.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service3.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service4.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service5.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service6.jpg')] bg-cover bg-center bg-no-repeat" />

                    </Slider>
                </div>

                <div className="w-full h-52 absolute bottom-0 bg-white z-30 flex justify-center items-center">
                    <p className="text-5xl text-[#B6A694]  font-semibold">GREEN SPACE</p>

                </div>

            </section>

            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow font-semibold">RESIDENCE LOBBY</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/service10.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service9.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service8.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service7.jpg')] bg-cover bg-center bg-no-repeat" />
                    </Slider>
                </div>

            </section>

            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow  font-semibold">RESIDENCE LOUNGE</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings2} className="!w-full !h-screen  ">
                        <div className="w-full h-screen px-2">
                            <div className="w-full h-screen  bg-[url('/assets/service/service11.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service12.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service13.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service14.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service15.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>
                    </Slider>
                </div>

            </section>

            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow  font-semibold">ROOFTOP SWIMMING POOL</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming1.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming2.jpg')] bg-cover bg-bottom bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming3.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming4.jpg')] bg-cover bg-center bg-no-repeat" />
                    </Slider>
                </div>

            </section>

            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden "
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow  font-semibold">FITNESS ROOM</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/gym1.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/gym2.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/gym3.jpg')] bg-cover bg-center bg-no-repeat" />

                    </Slider>
                </div>

            </section>



            <div className="bg-white w-full h-full pt-52">
                <Footer />
            </div>

        </Layout >
    );
}

export default Service;