import Layout from "../components/Layout";
import Head from "next/head";
import Slider from "react-slick";
import Footer from "../components/Footer";

const Service = () => {
    var settings = {
        speed: 1400,
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
        dots: true,
        infinite: true,
        fade: true,
    };

    var settings2 = {
        speed: 1400,
        centerMode: true,
        centerPadding: '250px',
        slidesToShow: 1,

        slidesToScroll: 1,
        arrows: true,
        dots: true,

    };

    return (
        <Layout>
            <Head>
                <title>Service - Residence Kimpinski</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section
                id="service"
                className="snap-start w-full h-[120vh] relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-full bg-gradient-to-b from-[#B5A191] absolute opacity-10 z-10" />
                <div className="max-w-7xl h-full w-full relative mx-4 md:mx-10 flex justify-center z-10">
                    <div className="mt-20 flex w-full absolute top-0 z-30">
                        <img
                            src="/assets/logo-w.svg"
                            alt="logo"
                            className="object-contain w-28 h-28"
                        />
                    </div>
                    <p className="text-[150px] font-Heleness  text-white pt-44">
                        S<span className="text-[90px] align-text-top">E</span>
                        RV
                        <span className="text-[90px] align-text-top">I</span>CE
                    </p>
                    <div></div>
                </div>
                <div id="content" className="snap-start w-full h-[120vh] bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-[120vh]  ">
                        <div className="w-full h-[120vh]  bg-[url('/assets/service/service1.jpg')] bg-cover bg-center bg-no-repeat" />


                    </Slider>
                </div>

            </section>

            <section
                id="service2"
                className="
                snap-start h-screen w-full bg-[url('/assets/paper.jpg')] bg-cover bg-no-repeat bg-fixed relative
                 flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-52 absolute bottom-0 bg-white z-30 flex justify-center items-center">
                    <p className="text-5xl text-[#B6A694]">GREEN SPACE</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/service2.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service3.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service4.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service5.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service6.jpg')] bg-cover bg-center bg-no-repeat" />

                    </Slider>
                </div>

            </section>

            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow">RESIDENCE LOBBY</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/service10.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service9.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service8.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/service7.jpg')] bg-cover bg-center bg-no-repeat" />
                    </Slider>
                </div>

            </section>


            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow">RESIDENCE LOUNGE</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings2} className="!w-full !h-screen  ">
                        <div className="w-full h-screen px-2">
                            <div className="w-full h-screen  bg-[url('/assets/service/service11.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service12.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service13.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service14.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>

                        <div className="w-full h-full px-2">

                            <div className="w-full h-screen  bg-[url('/assets/service/service15.jpg')] bg-cover bg-center bg-no-repeat" />
                        </div>
                    </Slider>
                </div>

            </section>

            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden mb-4"
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow">ROOFTOP SWIMMING POOL</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming1.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming2.jpg')] bg-cover bg-bottom bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming3.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/swimming4.jpg')] bg-cover bg-center bg-no-repeat" />
                    </Slider>
                </div>

            </section>


            <section
                id="service"
                className="snap-start w-full h-screen relative flex justify-center items-center overflow-hidden "
            >
                <div className="w-full h-52 absolute bottom-0  z-30 flex justify-center items-center">
                    <p className="text-5xl text-white drop-shadow font-bold">FITNESS ROOM</p>

                </div>


                <div id="content" className="snap-start w-full h-screen bg-white flex justify-center items-center absolute">
                    <Slider {...settings} className="!w-full !h-screen  ">
                        <div className="w-full h-screen  bg-[url('/assets/service/gym1.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/gym2.jpg')] bg-cover bg-center bg-no-repeat" />
                        <div className="w-full h-screen  bg-[url('/assets/service/gym3.jpg')] bg-cover bg-center bg-no-repeat" />

                    </Slider>
                </div>

            </section>

            <div className="bg-white w-full h-full pt-52">
                <Footer />
            </div>

        </Layout>
    );
}

export default Service;